export const vp_1 = "1vp";

export const vp_2 = "2vp";

export const vp_3 = "3vp";

export const vp_4 = "4vp";

export const vp_5 = "5vp";

export const vp_6 = "6vp";

export const vp_7 = "7vp";

export const vp_8 = "8vp";

export const vp_9 = "9vp";

export const vp_10 = "10vp";

export const vp_11 = "11vp";

export const vp_12 = "12vp";

export const vp_13 = "13vp";

export const vp_14 = "14vp";

export const vp_15 = "15vp";

export const vp_20 = "20vp";
export const vp_30 = "30vp";
export const vp_40 = "40vp";
export const vp_50 = "50vp";
export const vp_60 = "60vp";
export const vp_70 = "70vp";


export const fp_8 = "8fp";

export const fp_10 = "10fp";

export const fp_12 = "12fp";

export const fp_14 = "14fp";

export const fp_16 = "16fp";

export const fp_18 = "18fp";

export const fp_20 = "20fp";