/**
 * @author wzg
 * desc:
 */
export default class RoutePath {
  /**
   * index
   */
  static IndexPage = "pages/Index";
  /**
   * login
   */
  static LoginPage = "pages/LoginPage";
  /**
   * main
   */
  static MainPage = "pages/MainPage";
  /**
   * web view
   */
  static WebViewPage = "pages/WebViewPage";
  /**
   * web view
   */
  static ProjectListItemPage = "pages/ProjectListItemPage";
  /**
   * article type list page
   */
  static ArticleTypeListComponent = "pages/ArticleTypeListComponent";
  static WechatArticleComponent = "pages/WechatArticleComponent";
  static AuthorComponent = "pages/AuthorComponent";
  static StatementPageComponent = "pages/StatementPageComponent";
  static CollectArticleTypeListComponent = "pages/CollectArticleTypeListComponent";
  static NavigationPageComponent = "pages/NavigationPageComponent";
}